### PR TITLE
Migration formatting, model template adjustment

### PR DESCRIPTION
**Pull request by Braunson**
Adjusted migration class, file name and table name to match the
templates accordingly, adjusted formatting in the model - issue #32

### CODE REVIEW

**Comment by mlantz** [comment]
Please fix the tests :)

**Comment by Braunson** [comment]
Already ahead of you :)

**Comment by mlantz** [comment]
Cool I'll do the version release tonight unless you see anything else.

**Comment by Braunson** [comment]
Looks good to me.

**Pull request merged**
