### PR TITLE
Removing debug dump (artefact ?) and using FileSystem for exceptions

### PR DESCRIPTION
**Pull request by breakingrobot**

### CODE REVIEW

**Comment by casperboone** [comment]
Maybe also use FileSystem in DatabaseGenerator. And for consistency, it might be a good idea to replace file_put_contents with FileSystem's put.

**Comment by mlantz** [comment]
Why are we renaming the templates for Lumen?

**Comment by casperboone** [comment]
@mlantz That change was made before #12, so @breakingrobot probably still has to change it back ;)

**Comment by mlantz** [comment]
Also make sure for the file_contents_put ones that were appending files should be `$this->filesystem->append`

**Comment by mlantz** [comment]
And please remove the gitignore additions. I assume thats something PHPStorm stuffed in there?

**Comment by casperboone** [comment]
@breakingrobot Now both `ApiController`/`ApiRoutes` and `Controller`/`Routes` exist.

Using ->append() is indeed not necessary in that case, but it will make the code a lot cleaner.  So, it might be better to change that anyway.

**Pull request merged**
